language: node_js
node_js:
  - '10'
  - '8'
  - '6'
script: yarn test

jobs:
  include:
    - stage: analyze
      sudo: required
      dist: trusty
      node_js: '10'
      addons:
        sonarcloud:
          organization: 'jordansinko-github'
      script:
        - yarn cover
        - sonar-scanner
